services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
