services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ./bin/dev
    volumes:
      - .:/my_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    environment:
      REDIS_URL: redis://redis:6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/my_app
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379


volumes:
  postgres_data:
